{
 "title": "Kyverno ETCD Storage Observability",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total ETCD size allocated for reports-server",
   "type": "piechart",
   "description": "If the current size exceeds the total size the write operations to etcd will be stopped for reports",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "etcd_server_quota_backend_bytes{namespace=\"kyverno\",job=\"etcd\"} / 1024^3",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current disk space occupied by reports in MiB",
   "type": "timeseries",
   "description": "This value includes both non-obsolete (current) data and obsolete (older revisions) data.\nWhich data with compaction applied and data without compaction applied is shown with this metric\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "etcd_mvcc_db_total_size_in_bytes{namespace=\"kyverno\",job=\"etcd\"} / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETCD Space left in % ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100 * (etcd_mvcc_db_total_size_in_bytes{namespace=\"kyverno\",job=\"etcd\"} / on(pod) etcd_server_quota_backend_bytes{namespace=\"kyverno\",job=\"etcd\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ETCD Space occupied In % ",
   "type": "timeseries",
   "description": "(current_space/total_available) *100",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "100 * (etcd_mvcc_db_total_size_in_bytes{namespace=\"kyverno\",job=\"etcd\"} / on(pod) etcd_server_quota_backend_bytes{namespace=\"kyverno\",job=\"etcd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Logical Size After Compaction",
   "type": "timeseries",
   "description": "This metric tracks the total size of the database that is logically in use.\nOR\nThis metric reflects the amount of non-obsolete data in the database.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_use_in_bytes) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ETCD leader",
   "type": "timeseries",
   "description": "Leader etcd pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "etcd_server_is_leader", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Space that defragmentation process will Reclaim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "(etcd_mvcc_db_total_size_in_bytes{namespace=\"kyverno\",job=\"etcd\"} - etcd_mvcc_db_total_size_in_use_in_bytes{namespace=\"kyverno\",job=\"etcd\"}) / 1024 / 1024",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AVG Writes Per Second TO ETCD",
   "type": "timeseries",
   "description": "Average number of successful write operations per second (the write throughput) that our etcd cluste",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(etcd_server_proposals_applied_total{job=\"etcd\"}[5m])"
    }
   ]
  },
  {
   "title": "etcd Write Performance Latency (ms)",
   "type": "timeseries",
   "description": "It measures the time it takes for the database to commit a change. High values are a key indicator of a slow or overloaded etcd cluster, which can affect the entire Kubernetes control plane.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(etcd_server_apply_duration_seconds_bucket{job=\"etcd\"}[1m])) by (le, pod)\n) * 1000"
    }
   ]
  }
 ]
}